### ISSUE TITLE
很好用

### ISSUE THREAD

**Issue by hgitcast** [zhouyupeng/minHtml#1]
用了一下，很好的保留了原始项目结构并压缩了html文件，很nice，是我用过类似的脚本中最好的
如果js文件和css文件都能一起压缩就好了    不过已经非常棒了

**Comment by qiuyu303** [comment]
@hgitcast  安排上了，脚本已经更新，增加对js文件和css文件的压缩

**Comment by hgitcast** [comment]
> @hgitcast 安排上了，脚本已经更新，增加对js文件和css文件的压缩

ohhhhhhhhhh 太给力了 作者你太棒了~  更没想到的是这么久了还会去维护  感谢大佬能做出这么好这么方便的脚本   ~
